# Diwali Sales Data Analysis
**Module:** CC5061NI — Applied Data Science  
**Student:** Parashar Wagle  
**Date:** March 2026  

This notebook analyzes Diwali sales transaction data including customer 
demographics, product information and purchase behaviour.

## 1. Importing Libraries

Importing the necessary Python libraries for data analysis and visualization.

In [1]:
# Importing pandas for data manipulation and analysis
import pandas as pd
# Importing numpy for numerical operations
import numpy as np
## Import matplotlib for data visualization
import matplotlib.pyplot as plt

## 2. Loading the Dataset
Loading the dataset for Diwali Sales. This dataset necessitates unicode_escape encoding to properly manage special characters.

In [2]:
# Load the dataset
df = pd.read_csv('DiwaliSalesData_264932.csv', encoding='unicode_escape')
df

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370.0,NaN,NaN
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367.0,NaN,NaN
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213.0,NaN,NaN
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206.0,NaN,NaN
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188.0,NaN,NaN

In [3]:
# View first 5 rows
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

In [4]:
# View last t rows
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

## 3. Data Understanding
Understanding the structure, variables and potential challenges 
in the dataset before any cleaning or analysis begins.

The dataset contains **11,251 rows** and **15 columns** covering 
Diwali sales transactions across India.

In [5]:
# Number of rows and columns
df.shape

(11251, 15)

In [6]:
# All column names
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount', 'Status', 'unnamed1'],
      dtype='object')

In [7]:
# Data types of every column
df.dtypes

User_ID               int64
Cust_name            object
Product_ID           object
Gender               object
Age Group            object
Age                   int64
Marital_Status        int64
State                object
Zone                 object
Occupation           object
Product_Category     object
Orders                int64
Amount              float64
Status              float64
unnamed1            float64
dtype: object

In [8]:
# Summary statistics for all numerical columns
df.describe()

,User_ID,Age,Marital_Status,Orders,Amount,Status,unnamed1
count,1.125100e+04,11251.000000,11251.000000,11251.000000,11239.000000,0.0,0.0
mean,1.003004e+06,35.421207,0.420318,2.489290,9453.610858,NaN,NaN
std,1.716125e+03,12.754122,0.493632,1.115047,5222.355869,NaN,NaN
min,1.000001e+06,12.000000,0.000000,1.000000,188.000000,NaN,NaN
25%,1.001492e+06,27.000000,0.000000,1.500000,5443.000000,NaN,NaN
50%,1.003065e+06,33.000000,0.000000,2.000000,8109.000000,NaN,NaN
75%,1.004430e+06,43.000000,1.000000,3.000000,12675.000000,NaN,NaN
max,1.006040e+06,92.000000,1.000000,4.000000,23952.000000,NaN,NaN

In [9]:
# Column names, data types and non-null count per column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB

## 4. Checking Missing Values

Identifying which columns have missing values so we know 
what needs to be handled in the cleaning phase.

In [10]:
# Missing values per column
df.isnull().sum()

User_ID                 0
Cust_name               0
Product_ID              0
Gender                  0
Age Group               0
Age                     0
Marital_Status          0
State                   0
Zone                    0
Occupation              0
Product_Category        0
Orders                  0
Amount                 12
Status              11251
unnamed1            11251
dtype: int64

### Missing Value Observations

- **Amount** — 12 missing values, critical column.
- **Status** — 11,251 missing values, entire column is empty.
- **unnamed1** — 11,251 missing values, entire column is empty.
- All other columns have no missing values

## 5. Checking Unique Values

Listing distinct values for categorical columns to understand 
what categories exist in the data.

In [11]:
df['Zone'].unique()

array(['Western', 'Southern', 'Central', 'Northern', 'Eastern'],
      dtype=object)

In [12]:
df['Age Group'].unique()

array(['26-35', '0-17', '18-25', '55+', '46-50', '51-55', '36-45'],
      dtype=object)

In [13]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [14]:
df['Marital_Status'].unique()

array([0, 1])

In [15]:
df['Occupation'].unique()

array(['Healthcare', 'Govt', 'Automobile', 'Construction',
       'Food Processing', 'Lawyer', 'IT Sector', 'Media', 'Banking',
       'Retail', 'Hospitality', 'Aviation', 'Agriculture', 'Textile',
       'Chemical'], dtype=object)

In [16]:
df['State'].unique()

array(['Maharashtra', 'Andhra\xa0Pradesh', 'Uttar Pradesh', 'Karnataka',
       'Gujarat', 'Himachal Pradesh', 'Delhi', 'Madhya Pradesh',
       'Jharkhand', 'Kerala', 'Haryana', 'Bihar', 'Rajasthan',
       'Uttarakhand', 'Telangana', 'Punjab'], dtype=object)

In [17]:
# Count of each unique value — shows distribution across categories
df['Zone'].value_counts()

Zone
Central     4296
Southern    2695
Western     1955
Northern    1491
Eastern      814
Name: count, dtype: int64

In [18]:
df['Gender'].value_counts()

Gender
F    7842
M    3409
Name: count, dtype: int64

In [19]:

df['Age Group'].value_counts()

Age Group
26-35    4543
36-45    2286
18-25    1879
46-50     987
51-55     832
55+       428
0-17      296
Name: count, dtype: int64

In [20]:
# All 18 product categories
print("Product Categories:", df['Product_Category'].unique())
print()
print("Product Category Distribution")
print(df['Product_Category'].value_counts())

Product Categories: ['Auto' 'Hand & Power Tools' 'Stationery' 'Tupperware' 'Footwear & Shoes'
 'Furniture' 'Food' 'Games & Toys' 'Sports Products' 'Books'
 'Electronics & Gadgets' 'Decor' 'Clothing & Apparel' 'Beauty'
 'Household items' 'Pet Care' 'Veterinary' 'Office']

Product Category Distribution
Product_Category
Clothing & Apparel       2655
Food                     2493
Electronics & Gadgets    2087
Footwear & Shoes         1064
Household items           520
Beauty                    422
Games & Toys              386
Sports Products           356
Furniture                 353
Pet Care                  212
Office                    113
Stationery                112
Books                     103
Auto                      100
Decor                      96
Veterinary                 81
Tupperware                 72
Hand & Power Tools         26
Name: count, dtype: int64

## 6. Data Preparation

Describing the business relevance of key columns and confirming 
the dataset is ready for cleaning.
### Key Business Insights from Columns
- **Amount** is the core sales metric shows how much each customer spent
- **Orders** shows purchase frequency and buying history
- **Product_Category** helps identify which products sell best during Diwali
- **Zone and State** help identify which regions generate the most sales
- **Occupation and Age Group** help understand who the customers are

## 7. Data Cleaning

Cleaning the dataset by removing irrelevant columns, handling 
missing values and creating new useful columns for analysis.

### 7.1 Dropping Irrelevant Columns

Dropping Cust_name, User_ID and unnamed1 as they do not 
contribute to the analysis. Status column is also entirely 
empty so it will be dropped too.

In [21]:
# Dropping columns that are irrelevant or entirely empty
df = df.drop(columns=['Cust_name', 'User_ID', 'unnamed1', 'Status'])

# Checking it
df.columns

Index(['Product_ID', 'Gender', 'Age Group', 'Age', 'Marital_Status', 'State',
       'Zone', 'Occupation', 'Product_Category', 'Orders', 'Amount'],
      dtype='object')

### 7.2 Handling Missing Values

Removing rows where Amount is missing since it is a 
critical column for all sales analysis.

In [22]:
# Checking missing values before cleaning
df.isna().sum()

Product_ID           0
Gender               0
Age Group            0
Age                  0
Marital_Status       0
State                0
Zone                 0
Occupation           0
Product_Category     0
Orders               0
Amount              12
dtype: int64

In [23]:
# Remove rows with missing Amount values
df = df.dropna(subset=['Amount'])

# Confirm no missing values remain
df.isnull().sum()

Product_ID          0
Gender              0
Age Group           0
Age                 0
Marital_Status      0
State               0
Zone                0
Occupation          0
Product_Category    0
Orders              0
Amount              0
dtype: int64

### 7.3 Converting Age Group to Ordinal Categories

Converting Age Group from raw string ranges to proper 
ordered categories so it can be used correctly in analysis.

In [24]:
# Age group ranges to meaningful category names
age_group = {
    '0-17': 'Teen',
    '18-25': 'Young Adult',
    '26-35': 'Adult',
    '36-45': 'Middle Aged',
    '46-50': 'Senior',
    '51-55': 'Senior',
    '55+': 'Senior'
}

# Apply the mapping to create proper categories
df['Age Group'] = df['Age Group'].map(age_group)

# Convert to ordered categorical variable
df['Age Group'] = pd.Categorical(df['Age Group'],
                  categories=['Teen', 'Young Adult', 'Adult', 'Middle Aged', 'Senior'],
                  ordered=True)

# Checking the conversion
print(df['Age Group'].value_counts())

Age Group
Adult          4541
Middle Aged    2283
Senior         2240
Young Adult    1879
Teen            296
Name: count, dtype: int64