## Practicing a New data set

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('sleep_mobile_stress_dataset_15000.csv')

In [5]:
df

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,39,Male,Manager,8.05,45,8.91,4.33,10.00,1,40,259,10.00
14996,14997,22,Female,Student,6.44,80,6.00,5.22,10.00,2,41,231,7.54
14997,14998,51,Female,Software Engineer,7.01,78,7.27,5.37,8.66,4,93,288,7.78
14998,14999,56,Female,Software Engineer,7.89,6,5.70,5.71,9.56,1,91,47,9.98
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [6]:
df.head()

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99

In [7]:
df.tail()

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
14995,14996,39,Male,Manager,8.05,45,8.91,4.33,10.00,1,40,259,10.00
14996,14997,22,Female,Student,6.44,80,6.00,5.22,10.00,2,41,231,7.54
14997,14998,51,Female,Software Engineer,7.01,78,7.27,5.37,8.66,4,93,288,7.78
14998,14999,56,Female,Software Engineer,7.89,6,5.70,5.71,9.56,1,91,47,9.98
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [8]:
df.describe()

,user_id,age,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.00000,15000.000000,15000.000000,15000.000000
mean,7500.500000,38.488467,5.501528,59.708933,6.509683,6.246362,6.980247,1.99880,59.157133,160.890467,6.873009
std,4330.271354,12.007970,2.600085,34.641858,1.452689,1.713644,2.749382,1.41459,34.525705,80.856902,2.730482
min,1.000000,18.000000,1.000000,0.000000,4.000000,1.000000,1.000000,0.00000,0.000000,20.000000,1.000000
25%,3750.750000,28.000000,3.260000,29.000000,5.260000,5.000000,4.750000,1.00000,29.000000,92.000000,4.700000
50%,7500.500000,38.000000,5.490000,60.000000,6.490000,6.250000,7.380000,2.00000,59.000000,162.000000,7.380000
75%,11250.250000,49.000000,7.760000,90.000000,7.790000,7.500000,10.000000,3.00000,89.000000,231.000000,9.450000
max,15000.000000,59.000000,10.000000,119.000000,9.000000,10.000000,10.000000,4.00000,119.000000,299.000000,10.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  object
 3   occupation                        15000 non-null  object
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
dtypes: float64(5), int64(6), object(2)
memory usage: 1.5+ MB

In [10]:
df.sum()

user_id                                                                     112507500
age                                                                            577327
gender                              FemaleFemaleFemaleMaleFemaleMaleFemaleMaleMale...
occupation                          DesignerTeacherDesignerSoftware EngineerTeache...
daily_screen_time_hours                                                      82522.92
phone_usage_before_sleep_minutes                                               895634
sleep_duration_hours                                                         97645.25
sleep_quality_score                                                          93695.43
stress_level                                                                 104703.7
caffeine_intake_cups                                                            29982
physical_activity_minutes                                                      887357
notifications_received_per_day                                                2413357
mental_fatigue_score                                                        103095.13
dtype: object

In [11]:
df.isna().sum()

user_id                             0
age                                 0
gender                              0
occupation                          0
daily_screen_time_hours             0
phone_usage_before_sleep_minutes    0
sleep_duration_hours                0
sleep_quality_score                 0
stress_level                        0
caffeine_intake_cups                0
physical_activity_minutes           0
notifications_received_per_day      0
mental_fatigue_score                0
dtype: int64

In [12]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'daily_screen_time_hours',
       'phone_usage_before_sleep_minutes', 'sleep_duration_hours',
       'sleep_quality_score', 'stress_level', 'caffeine_intake_cups',
       'physical_activity_minutes', 'notifications_received_per_day',
       'mental_fatigue_score'],
      dtype='object')

In [15]:
## Peoples who sleeps less than six hours

In [13]:
df[df['sleep_duration_hours']<6]

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05
9,10,28,Female,Manager,9.75,46,4.73,5.52,10.00,3,56,121,10.00
13,14,41,Male,Student,4.67,82,4.23,4.66,7.93,4,43,286,9.04
16,17,19,Male,Freelancer,3.50,76,4.22,8.25,4.36,4,63,206,4.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14985,14986,58,Male,Manager,2.50,82,4.34,7.61,5.84,2,74,94,6.35
14990,14991,32,Female,Researcher,5.40,104,5.63,5.93,8.12,1,4,269,6.16
14992,14993,37,Female,Teacher,5.57,30,4.58,6.43,8.28,3,77,44,8.58
14998,14999,56,Female,Software Engineer,7.89,6,5.70,5.71,9.56,1,91,47,9.98
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [17]:
## People with high stress levels

In [18]:
df[df['stress_level']>7]

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
5,6,56,Male,Teacher,7.26,10,7.79,6.16,10.00,2,50,198,7.85
9,10,28,Female,Manager,9.75,46,4.73,5.52,10.00,3,56,121,10.00
10,11,41,Male,Designer,5.69,65,7.40,5.78,7.90,1,13,86,7.91
13,14,41,Male,Student,4.67,82,4.23,4.66,7.93,4,43,286,9.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,39,Male,Manager,8.05,45,8.91,4.33,10.00,1,40,259,10.00
14996,14997,22,Female,Student,6.44,80,6.00,5.22,10.00,2,41,231,7.54
14997,14998,51,Female,Software Engineer,7.01,78,7.27,5.37,8.66,4,93,288,7.78
14998,14999,56,Female,Software Engineer,7.89,6,5.70,5.71,9.56,1,91,47,9.98
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [19]:
## only students

In [14]:
df[df['occupation']=='students']

Empty DataFrame
Columns: [user_id, age, gender, occupation, daily_screen_time_hours, phone_usage_before_sleep_minutes, sleep_duration_hours, sleep_quality_score, stress_level, caffeine_intake_cups, physical_activity_minutes, notifications_received_per_day, mental_fatigue_score]
Index: []

In [15]:
df[(df['gender']=='Male') & (df['daily_screen_time_hours']>6)]

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
5,6,56,Male,Teacher,7.26,10,7.79,6.16,10.00,2,50,198,7.85
28,29,45,Male,Designer,8.10,3,7.85,6.87,9.62,4,65,232,8.74
32,33,54,Male,Student,9.43,26,8.47,3.12,10.00,3,115,136,9.70
36,37,56,Male,Designer,7.53,66,4.33,6.57,8.33,4,48,103,9.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14961,14962,18,Male,Freelancer,8.87,72,7.55,2.56,10.00,1,78,235,8.78
14979,14980,50,Male,Designer,6.52,102,7.50,4.63,9.27,0,12,107,10.00
14981,14982,21,Male,Freelancer,8.48,35,8.68,5.25,10.00,2,115,45,9.43
14991,14992,51,Male,Student,7.75,56,6.87,4.91,9.96,2,7,146,9.29
14995,14996,39,Male,Manager,8.05,45,8.91,4.33,10.00,1,40,259,10.00

In [27]:
## People with no caffine but high stress

In [16]:
df[(df['caffeine_intake_cups']==0) & (df['stress_level']>7)]

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
21,22,38,Female,Freelancer,4.95,113,8.97,4.85,8.99,0,47,148,9.36
71,72,38,Male,Researcher,9.88,64,8.93,4.67,10.00,0,84,181,10.00
74,75,41,Female,Doctor,8.73,31,8.23,3.68,10.00,0,70,51,10.00
78,79,46,Female,Designer,4.43,119,8.54,6.00,7.39,0,87,89,8.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14965,14966,24,Female,Student,8.50,31,4.90,4.82,10.00,0,37,259,8.40
14971,14972,32,Female,Software Engineer,9.95,8,4.14,4.75,10.00,0,56,138,9.04
14977,14978,46,Male,Teacher,5.63,88,4.54,5.70,7.10,0,36,140,7.41
14979,14980,50,Male,Designer,6.52,102,7.50,4.63,9.27,0,12,107,10.00
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [29]:
## # Who uses phone the most before sleep?

In [17]:
df.sort_values(by='phone_usage_before_sleep_minutes',ascending=False)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
2994,2995,25,Male,Doctor,9.10,119,4.53,4.56,10.00,3,40,132,9.60
8545,8546,50,Male,Software Engineer,3.60,119,7.62,6.60,5.96,0,97,57,5.62
13793,13794,55,Male,Freelancer,3.02,119,6.35,6.92,3.20,1,19,158,2.90
14682,14683,47,Female,Teacher,1.66,119,4.32,6.77,4.73,2,66,279,4.07
13805,13806,29,Male,Manager,1.84,119,8.77,6.20,4.48,0,105,121,3.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13444,13445,59,Male,Manager,6.97,0,4.07,7.80,9.21,2,96,130,9.93
2143,2144,18,Female,Researcher,8.48,0,6.97,6.52,8.89,2,119,83,8.54
7201,7202,40,Female,Researcher,6.31,0,8.68,6.16,7.74,1,52,184,6.27
6434,6435,31,Male,Researcher,1.17,0,8.11,8.06,1.73,4,43,255,1.25
11419,11420,50,Male,Student,3.95,0,5.52,8.43,4.12,2,93,63,4.49

In [31]:
## Who has the worst sleep quality?

In [33]:
df.sort_values(by='sleep_quality_score')

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
2266,2267,45,Female,Student,9.27,112,4.40,1.0,10.00,1,18,236,10.00
9592,9593,41,Female,Researcher,9.80,98,8.79,1.0,10.00,0,58,195,10.00
253,254,37,Male,Manager,9.63,114,4.64,1.0,10.00,4,25,233,10.00
5379,5380,29,Female,Freelancer,9.64,105,4.49,1.0,10.00,3,117,181,10.00
519,520,26,Female,Student,9.09,82,7.29,1.0,10.00,1,59,80,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12559,12560,29,Other,Software Engineer,1.24,6,8.46,10.0,1.02,1,39,165,1.52
13146,13147,20,Female,Doctor,1.35,2,4.30,10.0,1.00,4,76,295,1.00
225,226,57,Male,Software Engineer,2.21,34,4.12,10.0,1.00,0,29,174,1.11
13126,13127,30,Male,Student,1.24,9,6.61,10.0,1.00,2,43,185,1.00
2592,2593,46,Female,Software Engineer,1.09,38,7.67,10.0,1.13,3,40,119,1.00

In [34]:
## Most Stressed Peoples

In [18]:
df.sort_values(by='stress_level',ascending=False).head(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
7500,7501,22,Female,Designer,9.48,25,6.24,2.38,10.0,3,29,138,9.85
8483,8484,45,Female,Designer,8.23,68,7.54,5.61,10.0,4,103,52,8.81
8530,8531,56,Male,Researcher,6.10,56,8.68,5.32,10.0,4,7,190,10.00
8528,8529,43,Female,Teacher,7.89,82,8.18,4.29,10.0,4,54,266,10.00
8526,8527,41,Male,Researcher,8.13,78,5.50,5.52,10.0,1,118,137,10.00
8524,8525,58,Male,Manager,7.91,115,5.75,3.93,10.0,2,16,151,9.29
8523,8524,19,Male,Student,7.23,57,5.93,5.66,10.0,1,59,161,8.91
8521,8522,30,Other,Software Engineer,8.93,77,7.80,3.17,10.0,2,72,268,10.00
3005,3006,55,Male,Student,6.15,81,6.44,5.60,10.0,2,26,151,8.98
8516,8517,38,Male,Designer,9.50,88,8.77,4.50,10.0,0,5,192,10.00

In [37]:
## Average stress per occupation

In [19]:
df.groupby('occupation')['stress_level'].mean()

occupation
Designer             6.873855
Doctor               6.968330
Freelancer           6.899334
Manager              7.060031
Researcher           6.923217
Software Engineer    7.024262
Student              7.184879
Teacher              6.897791
Name: stress_level, dtype: float64

In [39]:
## Average sleep hours per gender

In [23]:
df.groupby('gender')['sleep_duration_hours'].mean()

gender
Female    6.504786
Male      6.508815
Other     6.580530
Name: sleep_duration_hours, dtype: float64

In [44]:
## Average screen time per occupation

In [26]:
df.groupby('occupation')['daily_screen_time_hours'].mean()

occupation
Designer             5.451655
Doctor               5.492612
Freelancer           5.409471
Manager              5.543012
Researcher           5.455237
Software Engineer    5.550402
Student              5.634970
Teacher              5.469950
Name: daily_screen_time_hours, dtype: float64

In [21]:
# Max mental fatigue per occupation

In [27]:
df.groupby('occupation')['mental_fatigue_score'].max()

occupation
Designer             10.0
Doctor               10.0
Freelancer           10.0
Manager              10.0
Researcher           10.0
Software Engineer    10.0
Student              10.0
Teacher              10.0
Name: mental_fatigue_score, dtype: float64

In [50]:
# Count of people per occupation

In [51]:
df.groupby('occupation')['user_id'].count()

occupation
Designer             1813
Doctor               1922
Freelancer           1891
Manager              1962
Researcher           1837
Software Engineer    1917
Student              1861
Teacher              1797
Name: user_id, dtype: int64

In [52]:
# Compare sleep quality and stress across occupations

In [53]:
pd.pivot_table(df,values=['sleep_quality_score','stress_level','mental_fatigue_score'],index='occupation',aggfunc='mean')

                   mental_fatigue_score  sleep_quality_score  stress_level
occupation
Designer                       6.745571             6.325527      6.873855
Doctor                         6.872877             6.255812      6.968330
Freelancer                     6.810153             6.276282      6.899334
Manager                        6.966682             6.213186      7.060031
Researcher                     6.804415             6.294017      6.923217
Software Engineer              6.920292             6.203782      7.024262
Student                        7.042198             6.111445      7.184879
Teacher                        6.810056             6.297551      6.897791

In [54]:
# Compare screen time and sleep by gender

In [55]:
pd.pivot_table(df,values=['daily_screen_time_hours','sleep_duration_hours'],index='gender',aggfunc='mean')

        daily_screen_time_hours  sleep_duration_hours
gender
Female                 5.487158              6.504786
Male                   5.508027              6.508815
Other                  5.597556              6.580530

In [56]:
# Label stress as High or Low

In [62]:
df['stress_level'].apply(lambda x: 'High' if x > 7 else 'low')

0         low
1         low
2         low
3        High
4         low
         ...
14995    High
14996    High
14997    High
14998    High
14999    High
Name: stress_level, Length: 15000, dtype: object

In [63]:
## Label sleep as Good or Bad

In [64]:
df['sleep_quality_score'].apply(lambda x: 'Good' if x >= 7 else 'Bad')

0        Good
1        Good
2         Bad
3         Bad
4         Bad
         ...
14995     Bad
14996     Bad
14997     Bad
14998     Bad
14999     Bad
Name: sleep_quality_score, Length: 15000, dtype: object

In [66]:
# Convert screen time hours to minutes

In [67]:
df['daily_screen_time_hours'].apply(lambda x: x *60)

0        195.6
1        111.0
2        182.4
3        540.0
4        211.2
         ...
14995    483.0
14996    386.4
14997    420.6
14998    473.4
14999    363.0
Name: daily_screen_time_hours, Length: 15000, dtype: float64

In [70]:
df.duplicated().sum()
df = df.drop_duplicates()

In [71]:
df.to_csv('updated_screentime_dataset.csv',index = False)