# ITTF Table Tennis Player Analysis

**Tools:** Python, Pandas, NumPy  
**Dataset:** [Kaggle - ITTF Players](https://www.kaggle.com/datasets/romanzdk/ittf-table-tennis-player-rankings-and-information)  
**Goal:** Analyze international table tennis player data 
— chose this dataset because I play table tennis competitively

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('ittf_player_info.csv')

In [4]:
df

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
1,113276,A. QADER Bakhtiyar,IRQ,Male,NaN,Active,NaN,NaN,NaN
2,100002,AAA Shirchin,MGL,Male,NaN,Active,NaN,NaN,NaN
3,114572,AACHARYA Yashwant,IND,Male,1990.0,Inactive,NaN,NaN,NaN
4,112267,AAL ALI Faisal,UAE,Male,1991.0,Active,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand
37617,116814,ZRAZHAVETS Mikalai,BLR,Male,1994.0,Active,NaN,NaN,NaN
37618,125506,ZRIMEC Tatjana,YUG,Female,NaN,Inactive,NaN,NaN,NaN
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [5]:
df.head()

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
1,113276,A. QADER Bakhtiyar,IRQ,Male,NaN,Active,NaN,NaN,NaN
2,100002,AAA Shirchin,MGL,Male,NaN,Active,NaN,NaN,NaN
3,114572,AACHARYA Yashwant,IND,Male,1990.0,Inactive,NaN,NaN,NaN
4,112267,AAL ALI Faisal,UAE,Male,1991.0,Active,NaN,NaN,NaN

In [6]:
df.tail(107)

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
37513,137569,ZHUBANOV Sanzhar,KAZ,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37514,115426,ZHUKOUSKAYA Lizaveta,BLR,Female,1993.0,Active,NaN,NaN,NaN
37515,123322,ZHUKOV Aleksei,RUS,Male,1989.0,Active,Left-handed,Attacker,Shakehand
37516,120621,ZHUKOV Artem,RUS,Male,1995.0,Active,NaN,NaN,NaN
37517,113011,ZHUR Greg,USA,Male,1970.0,Active,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand
37617,116814,ZRAZHAVETS Mikalai,BLR,Male,1994.0,Active,NaN,NaN,NaN
37618,125506,ZRIMEC Tatjana,YUG,Female,NaN,Inactive,NaN,NaN,NaN
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [7]:
df.shape

(37620, 9)

In [8]:
df.describe()

           Player ID    Birth year
count   37620.000000  28184.000000
mean   120369.414301   1975.867797
std     12184.899853    179.584493
min     90000.000000      0.000000
25%    109903.750000   1986.000000
50%    120576.500000   1995.000000
75%    130146.250000   2000.000000
max    146262.000000   2014.000000

In [9]:
df.isna().sum()

Player ID            0
Name                 0
Assoc              109
Gender               0
Birth year        9436
Activity           124
Playing hand     28113
Playing style    28113
Grip             28113
dtype: int64

In [10]:
df.fillna(method='ffill')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_6120\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
1,113276,A. QADER Bakhtiyar,IRQ,Male,1976.0,Active,-,-,-
2,100002,AAA Shirchin,MGL,Male,1976.0,Active,-,-,-
3,114572,AACHARYA Yashwant,IND,Male,1990.0,Inactive,-,-,-
4,112267,AAL ALI Faisal,UAE,Male,1991.0,Active,-,-,-
...,...,...,...,...,...,...,...,...,...
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand
37617,116814,ZRAZHAVETS Mikalai,BLR,Male,1994.0,Active,Right-handed,Attacker,Shakehand
37618,125506,ZRIMEC Tatjana,YUG,Female,1994.0,Inactive,Right-handed,Attacker,Shakehand
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [11]:
df = df.dropna()

In [12]:
df.isna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 9505 entries, 0 to 37619
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player ID      9505 non-null   bool
 1   Name           9505 non-null   bool
 2   Assoc          9505 non-null   bool
 3   Gender         9505 non-null   bool
 4   Birth year     9505 non-null   bool
 5   Activity       9505 non-null   bool
 6   Playing hand   9505 non-null   bool
 7   Playing style  9505 non-null   bool
 8   Grip           9505 non-null   bool
dtypes: bool(9)
memory usage: 157.8 KB

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df[df['Activity']=='Active']

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
5,145778,AALTONEN Gabriela,SWE,Female,2009.0,Active,Right-handed,Attacker,Shakehand
12,145022,AARRAD Wahiba,MAR,Female,2003.0,Active,Right-handed,Attacker,Shakehand
15,116168,AASEBO Anna,NOR,Female,1995.0,Active,Right-handed,Attacker,Shakehand
16,110761,AASEBO Marte,NOR,Female,1990.0,Active,Right-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37613,137860,ZOUBEK Simon,CZE,Male,2008.0,Active,Right-handed,Attacker,Shakehand
37614,137854,ZOUBKOVA Adela,CZE,Female,2006.0,Active,Right-handed,Attacker,Shakehand
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [15]:
df[df['Gender']=='Female']

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
5,145778,AALTONEN Gabriela,SWE,Female,2009.0,Active,Right-handed,Attacker,Shakehand
12,145022,AARRAD Wahiba,MAR,Female,2003.0,Active,Right-handed,Attacker,Shakehand
15,116168,AASEBO Anna,NOR,Female,1995.0,Active,Right-handed,Attacker,Shakehand
16,110761,AASEBO Marte,NOR,Female,1990.0,Active,Right-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37576,131741,ZOGHLAMI Maram,TUN,Female,2005.0,Active,Right-handed,Attacker,Shakehand
37582,144234,ZOLEK Zoja,SLO,Female,2007.0,Active,Right-handed,Attacker,Shakehand
37596,115179,ZONJIC Dijana,MNE,Female,1960.0,Active,Right-handed,Defender,Shakehand
37614,137854,ZOUBKOVA Adela,CZE,Female,2006.0,Active,Right-handed,Attacker,Shakehand
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [16]:
df[df['Playing hand']=='Left-handed']

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
32,137295,ABASSIA Cherif,TUN,Male,2006.0,Active,Left-handed,Attacker,Shakehand
86,116723,ABDEL-AZIZ Youssef,EGY,Male,2000.0,Active,Left-handed,Attacker,Shakehand
95,122183,ABDELAAL Adham,EGY,Male,2001.0,Active,Left-handed,Attacker,Shakehand
99,133560,ABDELAZIZ Mariam,EGY,Female,2001.0,Active,Left-handed,Attacker,Shakehand
113,137393,ABDELHASAN Ahmed,IRQ,Male,1987.0,Active,Left-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37553,131225,ZIRONOVA Ekaterina,RUS,Female,2002.0,Active,Left-handed,Attacker,Shakehand
37565,135401,ZLATKOV Luka,CRO,Male,2005.0,Active,Left-handed,Attacker,Shakehand
37579,136730,ZOHIL Borna,CRO,Male,2006.0,Active,Left-handed,Attacker,Shakehand
37605,137545,ZOU Hangcheng,CHN,Male,1999.0,Active,Left-handed,Attacker,Shakehand
37609,136627,ZOU Shang-Cheng,TPE,Male,2003.0,Active,Left-handed,Attacker,Shakehand

In [17]:
df[(df['Activity']=='Active') & (df['Gender']=='Male') & (df['Playing style']=='Attacker')]

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
20,136164,ABADLI Wafi Chams Eddine,ALG,Male,2007.0,Active,Right-handed,Attacker,Shakehand
32,137295,ABASSIA Cherif,TUN,Male,2006.0,Active,Left-handed,Attacker,Shakehand
42,137325,ABBAS Fadhel,BRN,Male,2004.0,Active,Right-handed,Attacker,Shakehand
68,144666,ABDALLA Yousif,QAT,Male,2009.0,Active,Right-handed,Attacker,Shakehand
86,116723,ABDEL-AZIZ Youssef,EGY,Male,2000.0,Active,Left-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37605,137545,ZOU Hangcheng,CHN,Male,1999.0,Active,Left-handed,Attacker,Shakehand
37609,136627,ZOU Shang-Cheng,TPE,Male,2003.0,Active,Left-handed,Attacker,Shakehand
37613,137860,ZOUBEK Simon,CZE,Male,2008.0,Active,Right-handed,Attacker,Shakehand
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand

In [18]:
df[df['Birth year'] > 2000]

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
5,145778,AALTONEN Gabriela,SWE,Female,2009.0,Active,Right-handed,Attacker,Shakehand
12,145022,AARRAD Wahiba,MAR,Female,2003.0,Active,Right-handed,Attacker,Shakehand
20,136164,ABADLI Wafi Chams Eddine,ALG,Male,2007.0,Active,Right-handed,Attacker,Shakehand
24,135207,ABARAVICIUTE Laura,LTU,Female,2004.0,Active,Right-handed,Attacker,Shakehand
32,137295,ABASSIA Cherif,TUN,Male,2006.0,Active,Left-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37582,144234,ZOLEK Zoja,SLO,Female,2007.0,Active,Right-handed,Attacker,Shakehand
37609,136627,ZOU Shang-Cheng,TPE,Male,2003.0,Active,Left-handed,Attacker,Shakehand
37613,137860,ZOUBEK Simon,CZE,Male,2008.0,Active,Right-handed,Attacker,Shakehand
37614,137854,ZOUBKOVA Adela,CZE,Female,2006.0,Active,Right-handed,Attacker,Shakehand
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand

In [19]:
df.sort_values(by='Birth year',ascending=False)

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
15453,145970,KANZA Kuka Joyce,COD,Male,2014.0,Active,Right-handed,Attacker,Shakehand
28867,146172,SAIDI Ahmed,TUN,Male,2012.0,Active,Right-handed,Attacker,Shakehand
17492,145971,KUMANAE Wembo Radi,COD,Male,2012.0,Active,Right-handed,Attacker,Shakehand
17942,145981,LANDU Mbenza Djanella,COD,Female,2012.0,Active,Right-handed,Attacker,Shakehand
1873,145978,ANGELANI Nsumbu Davina,COD,Female,2012.0,Active,Right-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
4773,137040,BUZAROVSKI Metodij ^^,MKD,Male,0.0,Active,-,-,-
34567,125893,VENTURA Byron,GUA,Male,0.0,Active,Right-handed,Attacker,Shakehand
36803,125561,YQUEL Rozenn,FRA,Female,0.0,Active,Right-handed,Attacker,Shakehand
9598,145377,FERNANDEZ Vianelkis ^^,DOM,Female,0.0,Active,-,-,-
34485,136704,VECCHIATO Riccardo ^^,ITA,Male,0.0,Active,-,-,-

In [20]:
df.sort_values(by='Assoc')

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
151,135114,ABDUL SAMI Khan Mohammad ^^,AFG,Male,1977.0,Active,-,-,-
1646,100521,AMIN MOHD Najibullah,AFG,Male,1990.0,Active,-,-,-
23335,145474,NAJAFI Nooria ^^,AFG,Female,1996.0,Active,-,-,-
8881,145475,ELYASSI Marwa ^^,AFG,Female,1995.0,Active,-,-,-
13314,145467,HOSSEINI Mohammad ^^,AFG,Male,1984.0,Active,-,-,-
...,...,...,...,...,...,...,...,...,...
1088,123614,ALAEBANI Ali,YEM,Male,2000.0,Active,Right-handed,Attacker,Shakehand
964,131392,AL-MAHAQERI Mahmood,YEM,Male,2003.0,Active,Right-handed,Attacker,Shakehand
875,123615,AL-DHAMARI Taha,YEM,Male,2001.0,Active,Right-handed,Attacker,Shakehand
28733,112817,SABRI Loai,YEM,Female,0.0,Active,-,-,-
12137,124065,HAMALAMBO Choolwe,ZAM,Male,1998.0,Active,-,-,-

In [21]:
df.groupby('Assoc')['Player ID'].count()

Assoc
AFG     5
ALB     4
ALG    68
ANG    15
ARG    93
       ..
VIN     9
WAL    33
WLF     5
YEM     7
ZAM     1
Name: Player ID, Length: 186, dtype: int64

In [22]:
df.groupby('Activity')['Player ID'].count()

Activity
Active      8987
Inactive     518
Name: Player ID, dtype: int64

In [24]:
df.groupby('Gender')['Birth year'].mean()

Gender
Female    1967.868468
Male      1938.365102
Name: Birth year, dtype: float64

In [25]:
df.groupby(['Gender','Playing style'])['Player ID'].count()

Gender  Playing style
Female  -                 606
        Attacker         3076
        Defender          241
Male    -                 975
        Attacker         4423
        Defender          184
Name: Player ID, dtype: int64

In [26]:
pd.pivot_table(df,values='Player ID',index='Gender',columns='Playing style',aggfunc='count')

Playing style    -  Attacker  Defender
Gender
Female         606      3076       241
Male           975      4423       184

In [27]:
df

,Player ID,Name,Assoc,Gender,Birth year,Activity,Playing hand,Playing style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
5,145778,AALTONEN Gabriela,SWE,Female,2009.0,Active,Right-handed,Attacker,Shakehand
10,110737,AARAS Pal,NOR,Male,1992.0,Inactive,Right-handed,Attacker,Shakehand
12,145022,AARRAD Wahiba,MAR,Female,2003.0,Active,Right-handed,Attacker,Shakehand
15,116168,AASEBO Anna,NOR,Female,1995.0,Active,Right-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37613,137860,ZOUBEK Simon,CZE,Male,2008.0,Active,Right-handed,Attacker,Shakehand
37614,137854,ZOUBKOVA Adela,CZE,Female,2006.0,Active,Right-handed,Attacker,Shakehand
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [28]:
df.rename(columns={'Player ID':'player_id','Birth year':'birth_year','Playing hand':'playing_hand','Playing style':'playing_style'},inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_6120\3457439583.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Player ID':'player_id','Birth year':'birth_year','Playing hand':'playing_hand','Playing style':'playing_style'},inplace=True)

In [29]:
df

,player_id,Name,Assoc,Gender,birth_year,Activity,playing_hand,playing_style,Grip
0,113207,A'ASA Junella,ASA,Female,1976.0,Active,-,-,-
5,145778,AALTONEN Gabriela,SWE,Female,2009.0,Active,Right-handed,Attacker,Shakehand
10,110737,AARAS Pal,NOR,Male,1992.0,Inactive,Right-handed,Attacker,Shakehand
12,145022,AARRAD Wahiba,MAR,Female,2003.0,Active,Right-handed,Attacker,Shakehand
15,116168,AASEBO Anna,NOR,Female,1995.0,Active,Right-handed,Attacker,Shakehand
...,...,...,...,...,...,...,...,...,...
37613,137860,ZOUBEK Simon,CZE,Male,2008.0,Active,Right-handed,Attacker,Shakehand
37614,137854,ZOUBKOVA Adela,CZE,Female,2006.0,Active,Right-handed,Attacker,Shakehand
37615,122986,ZOVKO Lovro,CRO,Male,2003.0,Active,Right-handed,Attacker,Shakehand
37616,114031,ZOVKO Vjekoslav,CRO,Male,1993.0,Active,Right-handed,Attacker,Shakehand
37619,121886,ZS.-SZABO Kira,HUN,Female,1998.0,Active,Right-handed,Attacker,Shakehand

In [34]:
df.groupby('playing_style')['Name'].count()

playing_style
-           1581
Attacker    7499
Defender     425
Name: Name, dtype: int64