In [63]:
import pandas as pd
import numpy as np

In [99]:
df = pd.read_csv('water.csv')

In [100]:
df

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1

In [101]:
df.dtypes

ph                 float64
Hardness           float64
Solids             float64
Chloramines        float64
Sulfate            float64
Conductivity       float64
Organic_carbon     float64
Trihalomethanes    float64
Turbidity          float64
Potability           int64
dtype: object

In [102]:
df['Potability']=df['Potability'].astype(float)

In [103]:
df.dtypes

ph                 float64
Hardness           float64
Solids             float64
Chloramines        float64
Sulfate            float64
Conductivity       float64
Organic_carbon     float64
Trihalomethanes    float64
Turbidity          float64
Potability         float64
dtype: object

In [104]:
df.rename(columns = {'Hardness':'Hard'}, inplace = True)

In [105]:
df.dtypes

ph                 float64
Hard               float64
Solids             float64
Chloramines        float64
Sulfate            float64
Conductivity       float64
Organic_carbon     float64
Trihalomethanes    float64
Turbidity          float64
Potability         float64
dtype: object

In [106]:
df.head(7)

,ph,Hard,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0.0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0.0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0.0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
5,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
6,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0.0

In [107]:
df.tail(7)

,ph,Hard,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3269,11.491011,94.812545,37188.826022,9.263166,258.930600,439.893618,16.172755,41.558501,4.369264,1.0
3270,6.069616,186.659040,26138.780191,7.747547,345.700257,415.886955,12.067620,60.419921,3.669712,1.0
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [108]:
df.loc[0:200, df.columns[0:4]]

           ph        Hard        Solids  Chloramines
0         NaN  204.890455  20791.318981     7.300212
1    3.716080  129.422921  18630.057858     6.635246
2    8.099124  224.236259  19909.541732     9.275884
3    8.316766  214.373394  22018.417441     8.059332
4    9.092223  181.101509  17978.986339     6.546600
..        ...         ...           ...          ...
196  9.868878  214.166235  15326.855914     3.351598
197  5.590614  229.192139  35370.735515     7.989641
198  5.554437  229.122829  31344.460394     7.761431
199  4.126529  125.474884  11215.945902     5.366011
200  5.970036  230.449329  16324.115196     5.293919

[201 rows x 4 columns]

In [109]:
df.iloc[0:201,0:4]

           ph        Hard        Solids  Chloramines
0         NaN  204.890455  20791.318981     7.300212
1    3.716080  129.422921  18630.057858     6.635246
2    8.099124  224.236259  19909.541732     9.275884
3    8.316766  214.373394  22018.417441     8.059332
4    9.092223  181.101509  17978.986339     6.546600
..        ...         ...           ...          ...
196  9.868878  214.166235  15326.855914     3.351598
197  5.590614  229.192139  35370.735515     7.989641
198  5.554437  229.122829  31344.460394     7.761431
199  4.126529  125.474884  11215.945902     5.366011
200  5.970036  230.449329  16324.115196     5.293919

[201 rows x 4 columns]

In [75]:
df.columns

Index(['ph', 'Hard', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity',
       'Organic_carbon', 'Trihalomethanes', 'Turbidity', 'Potability'],
      dtype='object')

In [110]:
df.shape

(3276, 10)

In [111]:
df.dtypes

ph                 float64
Hard               float64
Solids             float64
Chloramines        float64
Sulfate            float64
Conductivity       float64
Organic_carbon     float64
Trihalomethanes    float64
Turbidity          float64
Potability         float64
dtype: object

In [112]:
df.describe()

,ph,Hard,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [113]:
df.isna().sum()

ph                 491
Hard                 0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [114]:
df

,ph,Hard,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0.0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0.0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0.0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
...,...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [81]:
df = df.fillna(df.mean())

In [82]:
df.isna().sum()

ph                 0
Hard               0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [115]:
df = df.drop(columns=df.columns[2])

In [116]:
df

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0.0
1,3.716080,129.422921,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0.0
2,8.099124,224.236259,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0.0
3,8.316766,214.373394,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [117]:
df = df.drop(index=[0,1,2])

In [118]:
df

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3,8.316766,214.373394,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
5,5.584087,188.313324,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
6,10.223862,248.071735,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0.0
7,8.635849,203.361523,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0.0
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [119]:
df.duplicated().sum()
df = df.drop_duplicates()

In [120]:
df

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3,8.316766,214.373394,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
5,5.584087,188.313324,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
6,10.223862,248.071735,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0.0
7,8.635849,203.361523,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0.0
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [123]:
df_1 = [df['Sulfate'] > 0.5]

In [124]:
df

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3,8.316766,214.373394,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
5,5.584087,188.313324,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
6,10.223862,248.071735,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0.0
7,8.635849,203.361523,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0.0
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [125]:
df2 = [df['Turbidity']< 3]

In [126]:
df

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3,8.316766,214.373394,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
5,5.584087,188.313324,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
6,10.223862,248.071735,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0.0
7,8.635849,203.361523,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0.0
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [128]:
df3= [df['Conductivity'] > 300]

In [129]:
df

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3,8.316766,214.373394,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0.0
4,9.092223,181.101509,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0.0
5,5.584087,188.313324,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
6,10.223862,248.071735,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0.0
7,8.635849,203.361523,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0.0
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3272,7.808856,193.553212,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1.0
3273,9.419510,175.762646,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0
3275,7.874671,195.102299,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1.0

In [130]:
df[df['ph'] < 7]

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
5,5.584087,188.313324,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0.0
15,6.347272,186.732881,9.629596,364.487687,516.743282,11.539781,75.071617,4.376348,0.0
21,6.660212,168.283747,5.858769,310.930858,523.671298,17.884235,77.042318,3.749701,0.0
23,3.902476,196.903247,6.996312,NaN,444.478883,16.609033,90.181676,4.528523,0.0
24,5.400302,140.739062,10.056852,328.358241,472.874073,11.256381,56.931906,4.824786,0.0
...,...,...,...,...,...,...,...,...,...
3264,5.893103,239.269481,6.349561,341.256362,403.617560,18.963707,63.846319,4.390702,1.0
3268,6.702547,207.321086,7.708117,304.510230,329.266002,16.217303,28.878601,3.442983,1.0
3270,6.069616,186.659040,7.747547,345.700257,415.886955,12.067620,60.419921,3.669712,1.0
3271,4.668102,193.681735,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1.0
3274,5.126763,230.603758,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1.0

In [131]:
df.sort_values(by='ph')

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3014,0.000000,214.846144,7.897539,NaN,583.448849,7.702328,77.712891,4.928840,0.0
726,0.227499,152.530111,3.462492,283.693782,443.029232,13.201943,62.322711,3.545741,1.0
2928,0.975578,221.204114,7.615583,333.677843,439.112765,21.145954,NaN,2.533996,0.0
810,0.989912,133.216942,9.293289,444.375731,322.291191,10.430076,43.578466,5.160604,1.0
2899,1.431782,228.130383,6.214773,319.734136,495.379883,12.033344,61.141119,4.948443,0.0
...,...,...,...,...,...,...,...,...,...
3224,NaN,198.218700,7.419106,NaN,517.925946,11.711419,85.428785,3.345543,1.0
3229,NaN,203.204659,6.828936,NaN,384.597711,16.011328,72.911573,3.065910,1.0
3231,NaN,225.754109,5.892830,366.201583,418.272901,17.306832,103.912548,3.855895,1.0
3245,NaN,188.536608,7.129520,NaN,555.548534,16.959269,56.038702,4.331691,1.0
3260,NaN,134.736856,9.026293,NaN,428.213987,8.668672,74.773392,3.699558,1.0

In [132]:
df.sort_values(by='Turbidity', ascending=False)

,ph,Hard,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
492,NaN,169.188736,5.131839,342.937675,350.894362,19.334232,86.677328,6.739000,0.0
2921,7.611982,190.662804,5.224256,329.580679,577.444713,17.209367,65.333241,6.494749,0.0
382,5.772718,213.363545,8.630719,273.279448,465.559286,8.006208,59.964334,6.494249,1.0
1073,7.203439,168.445358,6.283250,271.892045,437.370863,16.410654,64.505923,6.389161,1.0
990,5.477283,165.436093,5.523011,370.893085,488.774595,17.265186,80.234797,6.357439,0.0
...,...,...,...,...,...,...,...,...,...
1927,NaN,179.756708,7.287310,NaN,311.093065,10.238271,42.075315,1.659799,1.0
2724,6.232011,208.668172,8.560039,NaN,325.344706,13.246995,33.380354,1.641515,1.0
1290,6.907380,210.279210,6.874702,294.015198,340.704978,18.253472,84.022119,1.496101,0.0
1892,7.080193,185.825726,8.806393,286.223876,355.937596,7.781493,39.623835,1.492207,1.0
3042,4.933106,162.184382,7.757702,317.935411,493.304069,14.261743,77.142104,1.450000,0.0

In [133]:
pivot = pd.pivot_table(df, values=['Sulfate','Hard','Conductivity'],index = 'ph' , aggfunc='mean')

In [134]:
print (pivot)

           Conductivity        Hard     Sulfate
ph
0.000000     583.448849  214.846144         NaN
0.227499     443.029232  152.530111  283.693782
0.975578     439.112765  221.204114  333.677843
0.989912     322.291191  133.216942  444.375731
1.431782     495.379883  228.130383  319.734136
...                 ...         ...         ...
12.246928    347.653054  217.368014  375.894758
13.175402    500.245952   47.432000  375.147315
13.349889    450.846369  152.776455  334.864070
13.541240    411.264465  187.606792         NaN
14.000000    460.745267  235.677458  381.097711

[2783 rows x 3 columns]

In [135]:
df.to_csv('updated_water.csv', index = False)